### ISSUE TITLE
IssueSelectorの誤実装

### ISSUE THREAD

**Issue by lpha-z** [onikiri/onikiri2#7]
`AgeIssueSelector`や`InorderIssueSelector`では、マージソートのように発行する命令を選んでいる。
しかし、`wokeUpOps`は古い順には並んではいない。
そのため、古い命令がwake-upしてもそのサイクルで選ばれないことがある。

`wokeUpOps`が古い順に並ぶように変更するのがよいのか、それともIssueSelectorの中で（マージソートではない）ソートを行うのがよいのか、あるいはもっと別の方法がよいのか。

**Comment by shioyadan** [comment]
ようそんなの気づいたね．
たぶん指摘自体は正しいと思う．

あれがマージソートぽくなってるのは，たしか真面目にソートすると無駄に処理量が増えるだろうからなるべくサボりたくてなんだよね．

wokeupOps に入ってる命令は最大でも発行幅以内で，大概は1とか2だと思うので，wokeupOps 内をソートするのがいいんでないかなと思う．

コードのわかりやすさとか綺麗さ的には，全部適当に結合して，えいやって全体にソートかけるのがいいんだろうけどね．

**Comment by lpha-z** [comment]
`wokeUpOps`には発行幅を超える数の命令が入り得るようです。
一つの命令に依存している命令の数は一つとは限らないためです。
たとえば、関数先頭でcallee-savedなレジスタをスピルする部分では、更新されたSPレジスタに依存した命令が大量にwake-upされます。
ハードウェアとしてそういうことが可能なのかは知りませんが、少なくとも今のコードではそのように動作します。

また、計算量の観点からは、`push_inorder`関数は挿入ソートを行っているため、Ο(NlogN)のソートを行うより低速なように思われます。この目的には二分ヒープが（定数倍も考慮に入れたうえで）適しているように思います。

**Comment by shioyadan** [comment]
あー，ごめん，勘違いしてた．確かにそうかも．
最大で発行キューの中身全員が起きるね．
大量のウェイクアップは，それは実際のハードウェアでも可能なように普通はできてます．

ただ，典型的には，ウェイクアップされるのは毎サイクル2つとかそんなもんであるのは違いないとは思う．

push_inorder 関数は~ ってのは，もし wokeUpOps を push_inorder でソートした場合のはなし？
それとも，この辺のリストをそもそも，挿入が早いデータ構造ベースにしとけということ？

（あとこれ，wokeUp じゃなくて wokenUp だね…

**Comment by lpha-z** [comment]
たしかに典型的にはwake-upされるのはごく少数の命令なので、`wokeUpOps`をソートするのがベストなように思われます。

`push_inorder`関数の話は、話が飛んでわかりづらくてすみません。
`wokeUpOps`ではなく、`Scheduler::m_readyOp`の構築自体が挿入ソートになっているので、IssueSelectorの計算量を気にする前にそっちを気にしないと意味がないという話でした。

**Comment by shioyadan** [comment]
つまり，Scheduler::m_readyOp 自体が今はただのリストになってるので，これを何らかの方法でオーダーの良い処理で挿入できる構造にしたほうが良い，と言うことだよね？

そう言う意味では，たぶん std::set に置き換えるだけで基本的には良いような気はする．けど，そもそも readyOp も典型的には要素数がかなり少ないと思うので，何も考えずに毎回ソートかましても実は速度ほとんどかわらんかもしれんね．（そしてその方が，コードはかなり見通しが良くなる気がする）

**Comment by lpha-z** [comment]
`AgeIssueSelector`は毎回ソートする方針で問題なさそうであることを確認しました(速度的にも、全体の0.2%程度で大したことはない)。

---

`InorderIssueSelector`では、Inorder性を保証するために`notReadyOps`の先頭の`GlobalSerialID`と比較している。しかし`notReadyOps`はソートされていないため、これも間違っている。

改修案としては、

* `push_back`を`push_inorder`に変える→その他のIssueSelectorを使ったとき無駄に遅くなるかも。
* `InorderIssueSelector`で毎回最小値を見つける→毎回計算するのが悔しいが他の箇所への影響はないしわかりやすい。

あたりでしょうか。

**Comment by shioyadan** [comment]
むかし Konata で確認したときは，見た目的には実行がちゃんと in-order になっていたから気づかなかったんだけど，これディスパッチ時にプログラムオーダー順に push_back されるから，リプレイが起きない限りは正しく動いてたんだね．

とりあえずは後者の毎回最小値を探すやつのが暫定的には良いと思う．
けど，この辺のリストはみんなプログラムオーダー順になっててくれよって気はするね･･･

**Comment by lpha-z** [comment]
修正をプルリクエスト #9 として投げました。

**Comment by shioyadan** [comment]
修正ありがとう。

普段はプルリクきたら、その前後で SPECCPU 2006 の全ベンチマークを走らせて（1G スキップ100M実行）、IPC や実行時間が大きく変わってないかや（本質的に変わるような変更なら変わってもいいんだけど）、そもそもクラッシュしないかを確認してるんだけど、ちょっとそこまで確認してみてもらえないかな？

**Comment by lpha-z** [comment]
実世界での実行時間は誤差の範囲で変化ありませんでした。
AgeIssueSelectorの修正について、シミュレーション結果のIPCは平均で0.2%ほど上がっていました(ほとんどのベンチマークでほとんど変化なし、444.namdと459.GemsFDTDで1%以上増加)。
InorderIssueSelectorの修正について、かなり大きく結果が変わっています。429.mcfで25%以上性能低下、481.wrfでも20%以上性能低下、などなどです。これはもともとがinorder性を守っていなくて不当に速かったのだと思われます。

**Comment by shioyadan** [comment]
InorderIssueSelector は，前のコードの何がおかしかったって，wokeup の中がソートされてなかったせいで，同時にウェイクアップされた命令のなかで（今関係ないけど，これ本当は wokenup だな）たまに順番が入れ替わることがあるかもってだけだと思うんだよね．not ready な命令列の中にそれより古い命令があったらいずれにせよ実行されないわけだ．

だから，25% も下がるってのはさすがにちょっとおかしい気がする．
コードを確認してみたんだけど，

    u64 minNotReadyID = UINT64_MAX;
    for( auto op : notReadyOps ) {
        minNotReadyID = std::min( minNotReadyID, op->GetGlobalSerialID() );
    }

これ，notReadyOps が空だと minNotReadyID が UINT64_MAX のままで，無条件に命令が実行されないことになっちゃわない？


あと，

    // Initialize only once for efficiency
    static SchedulingOps readyAndWokeUpOps;
    readyAndWokeUpOps.clear();

これは，そもそもそういうトリッキーなことはしないほうがいいと思う．
SchedulingOps はローカルなただの配列相当になるはずだけど，
ひょっとするとコンストラクタがサイズ分回ってる可能性はあって，
そこが気になるならもう少しサイズ小さくしとけばいいと思う．

**Comment by lpha-z** [comment]
`InorderIssueSelector`の間違いは、`wokeUpOps`だけではなく`notReadyOps`もソートされていないという点です。
A <- not ready
B <- woken up
C <- not ready
のように並んでいて、`notReadyOps`が[ C, A ]のようになっていた場合、元のコードでは、`notReadyOps`の先頭であるCより古いBは発行されてしまっていました。これは間違いで、IPCが高めに出てしまいます。

`notReadyOps`が空だと、`u64 minNotReadyID = UINT64_MAX`のままになるという指摘ですが（確かに頭がこんがらがるというのはわかりますが）、これは正しいです。

* std::min<u64>というモノイドの単位元は`UINT64_MAX`
* 実際もう少し下のコードを読むと、`if( op.ID > minNotReadyID ) { break; }`のようになっていて、この部分は`minNotReadyID == UINT64_MAX`ならば絶対に実行されない（からその下のselectしてる部分にたどり着く）

あたりで理解していただけると思います。


二つ目の指摘ですが、`SchedulingOps`の初期化はやたらに遅いので少し変な書き方になってしまいました……。
`OpIterator`のデフォルトコンストラクタが無意味に初期化コードを持っているのが遅くなっている原因のようです。
param.xmlでスケジューラのサイズがどれくらいを指定されるかが分からないため、安易にサイズを小さくするのはためらわれました。

`fixed_sized_buffer`ではなく`boost::container::static_vector`あたりを使えばましになるかもしれません。

**Comment by shioyadan** [comment]
notReadyOps は，たしかにそれはそうなんだけど，基本的には push_back で新しい命令は後ろに追加されていくので，リプレイが発生しなければ先頭が一番古いはずなんだよね．なので，そんなに性能さがんのかなぁと言うのはやっぱり気になる．

たとえばなんだけど，MCF で特定の箇所の10K命令ぐらいの区間でも before/after で大きな差がついているような部分がないか見てみて，もしそのぐらいの短さでも結構性能差が出ているようなところあったら，そこで Konata で何が起きてるかとか確認できないかね．

これはしかし，push したら自動的にテストを走らせてくれるやつを，やっぱりセットアップしないといかん気がする．


> notReadyOpsが空だと、u64 minNotReadyID = UINT64_MAXのままになるという指摘ですが（確かに頭がこんがらがるというのはわかりますが）、これは正しいです。

これはコードを見直してみたら，確かにそうだわ．ごめん．
ただ，min~ という名前の変数に，場合によって MAX が入ってるのは混乱のもとなので（判定時の不等号の判定が逆だとなりたたないし），size == 0 ? 0 : MAX; 的にしておいてもらえるとありがたい．

> std::minというモノイドの単位元はUINT64_MAX

これは何を言ってるのかわからなかった．


SchedulingOps は，そう言う事情であれば，コメントアウトされてる pool_vector の方にしてみればと思うけど，どうかな？

**Comment by lpha-z** [comment]
`size==0`の場合に`minNotReadyID`を0にしてしまうと、むしろ無条件に実行されないことになってしまいます。
> 判定時の不等号の判定が逆だと成り立たないし

はよくわかりませんでした。

少しわかりにくいので、`maxIssuableID`あたりの変数を作った方がよいでしょうか……？

mcfで大きく性能低下している原因の確認、`pool_vector`にしてみた場合の実世界での性能の確認は後でやっておきます。

**Comment by shioyadan** [comment]
> size==0の場合にminNotReadyIDを0にしてしまうと、むしろ無条件に実行されないことになってしまいます。

あー，そうね，ごめん，確かにその通りだわ．
出先で急いで書くもんじゃないね．

多分一番わかりやすいのは，size == 0 を判定条件に付けることなんじゃってきはするけど，どう？
もろもろの確認はありがとう，よろしくね．

**Comment by lpha-z** [comment]
`pool_vector`にした場合、変なコードを書かなくても実世界における性能は問題ありませんでした。

mcfが大きく性能低下している理由についてですが、どうやら以下のようなアクセスパターンが来ているようです(例えば、1Gスキップ後の(リタイア命令数で数えて)366K命令付近。ここを境に予測器の学習が飽和していることは確認済み)。

* ループの中の一つのロード命令は、いずれもキャッシュミスを起こして200cycle以上待つ。
* ループの別の回のロード命令との依存関係はないので、OoOなら並列に実行可能

間違った実装のInorderIssueSelectorを使うと、L1キャッシュミス発覚時のフラッシュでnotReadyOpsの先頭がかなり新しいOpになり、次のループのロード命令を発行してしまう(これは間違いで、IPCが不当に高く出る)、という仕組みになっていたようです。

**Comment by shioyadan** [comment]
調べてくれてありがとう．うーん，MCF は確かにタイトなループでゴリゴリキャッシュミス起こすので，あり得るシナリオではあるかな．

pool_vector の方は，特に性能に影響がでないようならよかった．

そのあたり，反映させたものをプッシュしておいてもらえればと思うんだけど，よろしくね．
あとは，フェッチャの方はどうだったかな？

**Comment by lpha-z** [comment]
ちょっと忙しくなるので、週末付近にやらせていただきます。
フェッチャーの方は、まだ手を付けていませんが、StallNextCycleを呼ぶ前にCancelStallPeriodを呼べば良さそうということで大丈夫でしょうか。

**Comment by shioyadan** [comment]
フェッチャの方は，その修正で大丈夫なはず．
分岐予測ミス以外のフラッシュ時も，それぞれなおさんとあかんかもしれない．

**Comment by lpha-z** [comment]
pull request #9 はマージ済み。
