### ISSUE TITLE
I want you to create cross-compiler for X86_64 of intel

### ISSUE THREAD

**Issue by ghost** [onikiri/onikiri2#8]
I'm working on a project so I want you to create cross-compiler for intel(64bit) because building it is bother. Could you make it?

**Comment by shioyadan** [comment]
We provide gcc 4.5.3 binaries.
You can download them from the following links.

http://www.mtl.t.u-tokyo.ac.jp/~onikiri2/archives/gcc/gcc-4.5.3-alpha-unknown-linux-gnu-bin.tar.gz
http://www.mtl.t.u-tokyo.ac.jp/~onikiri2/archives/gcc/gcc-4.5.3-powerpc64-unknown-linux-gnu-bin.tar.gz

You MUST unpack the archives to /opt/gcc/(alpha|ppc64)/4.5.3/. 
The gcc binaries do not work in other paths.

If you correctly unpack the files, you can use gcc from the following path.
/opt/gcc/(alpha|ppc64)/4.5.3/bin/(alpha|powerpc64)-unknown-linux-gnu-***
